matrix:
  include:

    # linux gcc
    - compiler: gcc
      env: testenv="linux gcc"
      

    # linux clang
    - compiler: clang
      env: testenv="linux clang"

    # os x cocoa port
    - language: objective-c
      env: testenv="os x cocoa port"
      os: osx
      compiler: clang
      before_script:
        - cd ../src

        # enable cmake to find x11 and xrandr
        - echo 'INCLUDE_DIRECTORIES("/opt/X11/include")' > temp.txt
        - echo 'LINK_DIRECTORIES("/opt/X11/lib")' >> temp.txt
        - cat temp.txt CMakeLists.txt > temp2.txt
        - rm CMakeLists.txt
        - mv temp2.txt CMakeLists.txt
        - cd ../build

    # mingw-w64 windows cross compile, libyabause only
    # needs qt and other deps built
    - compiler: gcc
      env: testenv="mingw-w64 windows cross compile, libyabause only"
      addons:
        apt:
          packages:
            - gcc-mingw-w64-x86-64
            - g++-mingw-w64-x86-64
            - binutils-mingw-w64-x86-64
            - mingw-w64-dev
      script:
        # create toolchain file so we can cross compile
        - echo 'SET(CMAKE_SYSTEM_NAME Windows)' > toolchain.cmake
        - echo 'SET(CMAKE_C_COMPILER   x86_64-w64-mingw32-gcc)' >> toolchain.cmake
        - echo 'SET(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)' >> toolchain.cmake
        - echo 'SET(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)' >> toolchain.cmake
        - cmake -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake -DYAB_PORTS= ..
        - make

    # compile runner and run yabauseut tests
    - compiler: gcc
      env: testenv="compile runner and run yabauseut tests"
      script:
        - cd ../src/runner
        - git clone git://github.com/lvandeve/lodepng.git
        - cd lodepng
        - cd ../../../build
        - cmake -DYAB_PORTS=runner -DSH2_DYNAREC=OFF -DYAB_WANT_C68K=OFF -DYAB_WANT_Q68=OFF -DYAB_WANT_OPENGL=OFF ..
        - make
        - cd src/runner
        # todo compile this instead
        - git clone git://github.com/d356/yabauseut-bin.git
        - cd yabauseut-bin
        - git reset --hard 9875a6f113bc796b68bd484245e709a04548d7cc
        - cd ..
        - ./yabause yabauseut-bin/YabauseUT.elf yabauseut-bin/vdp2_screenshots/



addons:
  coverity_scan:
    project:
      name: "d356/yabause"
      description: "Build submitted via Travis CI"
    notification_email: username@example.com
    build_command_prepend: "cd yabause; mkdir build; cd build; cmake ..;"
    build_command:   "make"
    branch_pattern: coverity

env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  # via the "travis encrypt" command using the project repo's public key
    - secure: "ACqDxwFJr0wwvAjyrHMyknxot9OJ4wg6F8pE+aEi6C1pL+VVlHfOUs0b+jREm+Icd2jZanv4UzPi3EIJxsIL82sbGkgFe0kILaE8UfycxYso7y10k+gwefI0cS3el+WcpyHX5rMablPE9FaDd4Cug8FsvJjwTsW88/JosCepn2IZ6HtMAheuNZnDi5D2nCEvJHkE1vXzGZrfgu6rfY2hXOv/wUqegx2XMJq0vGdOn9JE92UqRaLkfNZXlRsCLWre0isy/AO0QdRwmV9668aYrRFDtfEdoMy2xWuCNpeWWenxz5ZniPJrPaCOQlOtlPBgTzuu6HZoR0JLJKApa0IflkPByKdOLWXwOA7W4RWbonfHR5LCm2z3SO0MhkTk/c7UE3+a6GtfwH+0KAl+V6WQ0MfVhVwlY/UG+KhQbpJSLLP70H3zjGU+4Dbmm9Ogt3Je2AmxzHtmsuyyJUI7Z6gDmu3aUDYuLrPVSlIA96i/YoZkEdXJLUphwGHvDzT+vK8H1IBgXMVKumD3I0PHY1AonQaOaCJ5ihFPecGqqRiETQndNKkVYdNDLdCnEYKgLQFppqgfcainyAhyyK9wmqracPEoq09GTnv+je82hoj8Dm68xqLbWMKQAhm1ArPClNCOU43KR03gve6Cr6ebLq2rSQqEiaeQfIwULhKvdUxLYb4="

language: cpp

sudo: false

before_install:
  - cd yabause
  - mkdir build
  - cd build

script:
  - cmake ..
  - make