environment:
  MINGW: C:\Qt\Tools\mingw492_32
  CMAKE_BUILD_TYPE: Release
  # set to d if debug build
  qt_dll_suffix: ""

  matrix:
    # filename on the sdl website
      sdl_filename: SDL2-devel-2.0.3-mingw.tar.gz
      sdl_arch: x86

    # included directx headers incompatible with mingw
      cmake_args: "-DYAB_NETWORK=ON -DYAB_WANT_GDBSTUB=ON"

    # MSYS2 x86_64 build
    - compiler_type: "msys2-mingw-w64-x86_64"

shallow_clone: true

init:
  # cmake errors if sh on the path
  # - rm "C:\Program Files (x86)\Git\bin\sh.exe"
  - rm "C:\Program Files\Git\usr\bin\sh.exe"
  # cpack won't work because of chocolatey sharing the same name
  - rm "C:\ProgramData\chocolatey\bin\cpack.exe"
  - set Path=%MINGW%\bin;%Path%

before_build:
  # fetch appropriate sdl lib for visual studio or mingw
  - cd c:\

  # generate project files or makefiles
  - cd C:\projects\yabause\yabause
  - mkdir build
  - cd build

  #MSYS2
  - if ["%compiler_type%"]==["msys2-mingw-w64-x86_64"] set MSYSTEM=MINGW64
  - if ["%compiler_type%"]==["msys2-mingw-w64-x86_64"] set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\msys64;%PATH%
  - if ["%compiler_type%"]==["msys2-mingw-w64-x86_64"] C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"
  # build mini18n
  - if ["%compiler_type%"]==["msys2-mingw-w64-x86_64"] C:\msys64\usr\bin\bash -lc "cd C:\projects ; mkdir build_mini18n ; cd build_mini18n ; cmake -G\"MSYS Makefiles\" .. ; make"
  - if ["%compiler_type%"]==["msys2-mingw-w64-x86_64"] C:\msys64\usr\bin\bash -lc "pacman --noconfirm --needed -S mingw64/mingw-w64-x86_64-SDL2 mingw-w64-x86_64-binutils mingw64/mingw-w64-x86_64-qt5 mingw-w64-x86_64-crt-git mingw-w64-x86_64-headers-git mingw64/mingw-w64-x86_64-libwebp"
  - if ["%compiler_type%"]==["msys2-mingw-w64-x86_64"] C:\msys64\usr\bin\bash -lc "cd C:/projects/yabause/yabause/build ; cmake -G\"MSYS Makefiles\" -DCMAKE_BUILD_TYPE=Release -DDirectX_INCLUDE_DIR=C:/msys64/mingw64/x86_64-w64-mingw32/include -DYAB_WANT_DIRECTSOUND=ON -DYAB_WANT_DIRECTINPUT=ON -DYAB_NETWORK=ON -DYAB_WANT_GDBSTUB=ON -DMSYS2_BUILD=ON -DCMAKE_PREFIX_PATH=\"C:/msys64/mingw64/bin;C:/msys64/mingw64/include;C:/msys64/mingw64/lib;C:/msys64/mingw64/x86_64-w64-mingw32/include;C:/msys64/mingw64/x86_64-w64-mingw32/lib\" -DSDL2_LIBRARY=C:/msys64/mingw64/lib/libSDL2.dll.a .."

build_script:
  - if ["%compiler_type%"]==["msys2-mingw-w64-x86_64"] C:\msys64\usr\bin\bash -lc "cd C:/projects/yabause/yabause/build ; make "