environment:
  MINGW: C:\Qt\Tools\mingw492_32
  CMAKE_BUILD_TYPE: Release
  # set to d if debug build
  qt_dll_suffix: ""

  matrix:
    # MSYS2 x86_64 build
    - compiler_type: "msys2-mingw-w64-x86_64"

shallow_clone: true

init:
  # cmake errors if sh on the path
  # - rm "C:\Program Files (x86)\Git\bin\sh.exe"
  - rm "C:\Program Files\Git\usr\bin\sh.exe"
  # cpack won't work because of chocolatey sharing the same name
  - rm "C:\ProgramData\chocolatey\bin\cpack.exe"
  - set Path=%MINGW%\bin;%Path%

before_build:
  # fetch appropriate sdl lib for visual studio or mingw
  - cd c:\

  # generate project files or makefiles
  - cd C:\projects\yabause\yabause
  - mkdir build
  - cd build

  #MSYS2
  - if ["%compiler_type%"]==["msys2-mingw-w64-x86_64"] C:\projects\yabause\yabause\appveyor-mingw.cmd

build_script:
  - if ["%compiler_type%"]==["msys2-mingw-w64-x86_64"] C:\msys64\usr\bin\bash -lc "cd C:/projects/yabause/yabause/build ; make "